// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for menu documents */
interface MenuDocumentData {
    /**
     * Slice Zone field in *menu*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<MenuDocumentDataSlicesSlice>;
}
/**
 * Slice for *menu → Slice Zone*
 *
 */
type MenuDocumentDataSlicesSlice = MenuNavigationSlice;
/**
 * menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for pagina_inicial documents */
interface PaginaInicialDocumentData {
    /**
     * title field in *pagina_inicial*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pagina_inicial.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *pagina_inicial*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: pagina_inicial.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PaginaInicialDocumentDataSlicesSlice>;
}
/**
 * Slice for *pagina_inicial → Slice Zone*
 *
 */
type PaginaInicialDocumentDataSlicesSlice = HeroSectionSlice | FeaturesSectionsSlice;
/**
 * pagina_inicial document from Prismic
 *
 * - **API ID**: `pagina_inicial`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PaginaInicialDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<PaginaInicialDocumentData>, "pagina_inicial", Lang>;
export type AllDocumentTypes = MenuDocument | PaginaInicialDocument;
/**
 * Item in FeatureSection → Items
 *
 */
export interface FeaturesSectionsSliceDefaultItem {
    /**
     * Título field in *FeatureSection → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_sections.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Descrição field in *FeatureSection → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Descreva aqui o benefício
     * - **API ID Path**: features_sections.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * image field in *FeatureSection → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: features_sections.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for FeatureSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FeaturesSections`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSectionsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<FeaturesSectionsSliceDefaultItem>>;
/**
 * Item in FeatureSection → Items
 *
 */
export interface FeaturesSectionsSlice4ColsItem {
    /**
     * Título field in *FeatureSection → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: features_sections.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Descrição field in *FeatureSection → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Descreva aqui o benefício
     * - **API ID Path**: features_sections.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * 4 Colunas variation for FeatureSection Slice
 *
 * - **API ID**: `4Cols`
 * - **Description**: `FeaturesSections`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSectionsSlice4Cols = prismicT.SharedSliceVariation<"4Cols", Record<string, never>, Simplify<FeaturesSectionsSlice4ColsItem>>;
/**
 * Slice variation for *FeatureSection*
 *
 */
type FeaturesSectionsSliceVariation = FeaturesSectionsSliceDefault | FeaturesSectionsSlice4Cols;
/**
 * FeatureSection Shared Slice
 *
 * - **API ID**: `features_sections`
 * - **Description**: `FeaturesSections`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeaturesSectionsSlice = prismicT.SharedSlice<"features_sections", FeaturesSectionsSliceVariation>;
/**
 * Primary content in HeroSection → Primary
 *
 */
interface HeroSectionSliceDefaultPrimary {
    /**
     * Título field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Descrição field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * CTA Texto field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_label: prismicT.KeyTextField;
    /**
     * CTA Link field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_link: prismicT.KeyTextField;
}
/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeroSection*
 *
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;
/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: `HeroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSlice = prismicT.SharedSlice<"hero_section", HeroSectionSliceVariation>;
/**
 * Primary content in MenuNavigation → Primary
 *
 */
interface MenuNavigationSliceDefaultPrimary {
    /**
     * CTA Link field in *MenuNavigation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu_navigation.primary.cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_link: prismicT.KeyTextField;
    /**
     * CTA Texto field in *MenuNavigation → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu_navigation.primary.cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_label: prismicT.KeyTextField;
}
/**
 * Item in MenuNavigation → Items
 *
 */
export interface MenuNavigationSliceDefaultItem {
    /**
     * Url field in *MenuNavigation → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu_navigation.items[].url
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    url: prismicT.KeyTextField;
    /**
     * Nome field in *MenuNavigation → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu_navigation.items[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
}
/**
 * Default variation for MenuNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MenuNavigation`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuNavigationSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MenuNavigationSliceDefaultPrimary>, Simplify<MenuNavigationSliceDefaultItem>>;
/**
 * Slice variation for *MenuNavigation*
 *
 */
type MenuNavigationSliceVariation = MenuNavigationSliceDefault;
/**
 * MenuNavigation Shared Slice
 *
 * - **API ID**: `menu_navigation`
 * - **Description**: `MenuNavigation`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MenuNavigationSlice = prismicT.SharedSlice<"menu_navigation", MenuNavigationSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { MenuDocumentData, MenuDocumentDataSlicesSlice, MenuDocument, PaginaInicialDocumentData, PaginaInicialDocumentDataSlicesSlice, PaginaInicialDocument, AllDocumentTypes, FeaturesSectionsSliceDefaultItem, FeaturesSectionsSliceDefault, FeaturesSectionsSlice4ColsItem, FeaturesSectionsSlice4Cols, FeaturesSectionsSliceVariation, FeaturesSectionsSlice, HeroSectionSliceDefaultPrimary, HeroSectionSliceDefault, HeroSectionSliceVariation, HeroSectionSlice, MenuNavigationSliceDefaultPrimary, MenuNavigationSliceDefaultItem, MenuNavigationSliceDefault, MenuNavigationSliceVariation, MenuNavigationSlice };
    }
}
