// Code generated by Slice Machine. DO NOT EDIT.

import FeatureList from './FeatureList';
import FeatureSection from './FeatureSection';
import HeroSection from './HeroSection';
import LogoSection from './LogoSection';
import MenuNavigation from './MenuNavigation';
import ProductSection from './ProductSection';
import ServiceSection from './ServiceSection';

export {
	FeatureList,
	FeatureSection,
	HeroSection,
	LogoSection,
	MenuNavigation,
	ProductSection,
	ServiceSection,
};

export const components = {
	feature_list: FeatureList,
	features_sections: FeatureSection,
	hero_section: HeroSection,
	logo_section: LogoSection,
	menu_navigation: MenuNavigation,
	tabs_section: ProductSection,
	service_section: ServiceSection,
};
