// Code generated by Slice Machine. DO NOT EDIT.

import HeroSection from './HeroSection';
import MenuNavigation from './MenuNavigation';

export {
	HeroSection,
	MenuNavigation,
};

export const components = {
	hero_section: HeroSection,
	menu_navigation: MenuNavigation,
};
