// Code generated by Slice Machine. DO NOT EDIT.

import FeatureSection from './FeatureSection';
import HeroSection from './HeroSection';
import MenuNavigation from './MenuNavigation';

export {
	FeatureSection,
	HeroSection,
	MenuNavigation,
};

export const components = {
	features_sections: FeatureSection,
	hero_section: HeroSection,
	menu_navigation: MenuNavigation,
};
